version: '3'
services:
  app:
    ports:
      - ${APP_PORT:-80}:80
      - ${APP_PORT:-443}:443
    volumes:
        - .:/var/www:cached
        - /var/www/node_modules
  db:
    container_name: geencijfer-db
    image: mysql:5.7
    volumes:
     - data:/var/lib/mysql
    environment:
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - ${DB_PORT:-3306}:3306
    networks:
      - appnet
  node:
    container_name: geencijfer-node
    image: geencijfer/node
    build: docker/node
    volumes:
      - .:/var/www
      - ~/.ssh:/root/.ssh
volumes:
  data:
    driver: "local"
