version: '3'
services:
  app:
    container_name: xdebug-demo-app
    build: docker/app
    ports:
      - ${APP_PORT:-80}:80
      - ${APP_PORT:-443}:443
    volumes:
      - .:/var/www:cached
    networks:
        - appnet
networks:
  appnet:
    driver: bridge
